version: '3'
services:
  tos-http:
    build: .
    image: tos-app
    command: start-http
    ports:
      - 80:80
    volumes:
      - ./certs:/app/certs
  tos-https:
    image: tos-app
    command: start-https
    ports:
      - 443:443
    volumes:
      - ./certs:/app/certs